QUESTIONS = [
    # Marcus Aurelius — self-discipline & inner life
    "What is within my control today, and am I focusing only on that?",
    "Am I acting as my best self would, or just as my habits demand?",
    "What would Marcus Aurelius say about how I spent my time today?",
    "Did I treat every person I met today as worthy of dignity?",
    "What opinion am I holding that might not be true?",
    "Am I disturbed by something external, or by my judgment of it?",
    "What role is my ego playing in a current conflict I have?",
    "What would I do today if I knew it was my last?",
    "Am I doing what is necessary, or what is comfortable?",
    "What does my body want that my mind should refuse?",
    "What am I tolerating in myself that I would criticize in others?",
    "Where am I acting from fear rather than reason?",
    "Is my anger justified, or is it a sign of weakness?",
    "What small injustice did I commit today — even silently?",
    "Who in my life am I not appreciating enough?",

    # Seneca — time & mortality
    "How much of today did I truly own, and how much did I give away?",
    "If this day were subtracted from my life, what would I have lost?",
    "Am I living as though I have unlimited time?",
    "What task am I postponing that I know I should do now?",
    "Who is the person I am becoming through my daily choices?",
    "What would Seneca say about how I spent my leisure time?",
    "Am I borrowing from the future to avoid the present?",
    "What comfort am I clinging to that is making me weaker?",
    "How much of my worry today was about things that never happened?",
    "What would I regret not having done if I died tonight?",
    "Am I spending time with people who make me better?",
    "What old wound am I still letting drain my energy?",
    "Is my busyness today a sign of productivity or of avoidance?",
    "What truth am I not saying because it feels uncomfortable?",
    "Am I living my values or just describing them?",

    # Epictetus — freedom & acceptance
    "What have I been treating as mine that was never truly mine?",
    "Where did I confuse preference with necessity today?",
    "What person did I try to change instead of accepting?",
    "Am I free, or am I enslaved to someone's opinion of me?",
    "What would I do if I had nothing left to lose?",
    "Where did I surrender my peace to something outside me?",
    "What role am I playing that isn't really me?",
    "Did I react to an insult, or did I choose my response?",
    "What is the hardship I face teaching me about myself?",
    "Am I using difficulty as an excuse or as training?",
    "What do I wish others understood about me that I have never said?",
    "Where am I complaining instead of acting?",
    "What limitation did I accept today that I should have challenged?",
    "Am I practicing what I preach when no one is watching?",
    "What would a free person do in my current situation?",

    # Virtue & character
    "Did I do something today that required courage?",
    "Was I just today, even when it cost me something?",
    "Did I practice temperance, or did I indulge what I should not have?",
    "What virtue did I exercise least this week?",
    "Where was I dishonest — with myself or with others?",
    "What would a person of perfect integrity have done differently today?",
    "Who am I in private, when no one is evaluating me?",
    "What is one small thing I did well today that I tend to overlook?",
    "Did I keep my word today, in every sense?",
    "What would I be ashamed to admit I spent time on today?",
    "Where did I choose the easier wrong over the harder right?",
    "What habit am I building with today's actions?",
    "Did I give my best effort to whatever I worked on?",
    "How would I judge someone who acted exactly as I acted today?",
    "Is there a gap between who I say I am and who I actually am?",

    # Relationships & others
    "Did I listen today, or was I only waiting to speak?",
    "Who did I serve today, and was it enough?",
    "Whose life is a little better because of my presence today?",
    "Did I assume the worst of someone when the best was equally possible?",
    "What argument did I win at the cost of a relationship?",
    "Am I in any relationship where I am not being honest?",
    "What would it mean to love the people around me more completely?",
    "Whose suffering am I ignoring because it is inconvenient to notice?",
    "Did I compete when I should have cooperated?",
    "Did I cooperate when I should have stood firm?",
    "What grudge am I holding that is only hurting me?",
    "Did I gossip today, and what did that say about me?",
    "What person in my life deserves a direct and honest thank you?",
    "Am I demanding of others what I refuse to demand of myself?",
    "Who challenges me most, and what are they teaching me?",

    # Wealth, desire & simplicity
    "What do I own that owns me back?",
    "What would I not give up, and is that revealing?",
    "Am I working to live, or living to work?",
    "What desire, if fulfilled, would still not be enough?",
    "What is the simplest version of a life I would be proud of?",
    "Did envy shape any of my thinking today?",
    "What would I have if I stopped wanting what I don't need?",
    "Am I measuring myself by wealth or by character?",
    "What sacrifice would prove I truly believe what I say I value?",
    "Is my relationship with money honest?",
    "What am I chasing that would not satisfy me even if I caught it?",
    "What luxury have I confused with necessity?",
    "What did I buy recently that I did not need?",
    "What am I afraid to live without that I could live without?",
    "What is the real cost — in time and freedom — of what I want?",

    # Obstacles & adversity
    "What obstacle today could I reframe as training?",
    "Where did I give up too soon?",
    "What is the worst realistic outcome of my current fear?",
    "Have I prepared today for the difficulty tomorrow might bring?",
    "What failure am I still not forgiving myself for?",
    "Where did I blame circumstance when I should have blamed my response?",
    "What discomfort am I avoiding that would make me stronger?",
    "What would I do if I trusted my ability to handle whatever comes?",
    "Am I solving the actual problem, or managing my feelings about it?",
    "What hard conversation am I avoiding because I fear the outcome?",
    "What problem looks unsolvable only because I haven't sat with it long enough?",
    "Did I ask for help when I needed it, or did I resist out of pride?",
    "What is suffering teaching me that comfort never could?",
    "How much of what stressed me today will matter in five years?",
    "What would the strongest version of me do right now?",

    # Purpose & meaning
    "What am I building with my life, and does it reflect what I believe?",
    "Am I on a path I chose, or one I drifted into?",
    "What would I regret not having tried?",
    "What is the one thing I could do that everything else would follow from?",
    "Am I contributing something to the world, or only extracting from it?",
    "What does my daily schedule reveal about my true priorities?",
    "If I imagine my life at 80, what would I wish I had done more of?",
    "What legacy am I building — intentionally or by default?",
    "What work am I doing that will outlast me?",
    "What does my soul need today that my schedule is not providing?",
    "Am I clear on what I stand for, and does my life reflect it?",
    "What would I do differently if I knew I would succeed?",
    "What are the excuses I keep giving myself for not living fully?",
    "Is my current path one a wise person would counsel me to stay on?",
    "What question about my life am I most afraid to answer honestly?",

    # Gratitude & presence
    "What did I take for granted today that I could have been grateful for?",
    "Did I notice beauty today, or was I too distracted to see it?",
    "What ordinary moment today was quietly extraordinary?",
    "Am I present with the people in front of me, or elsewhere in my mind?",
    "What do I have right now that a past version of me would have been grateful for?",
    "Did I rush through today, or did I inhabit it?",
    "What loss, if it happened tomorrow, would teach me to love better today?",
    "How often today did I experience the present rather than plan for the future?",
    "What would I see in this day if I looked with gratitude instead of complaint?",
    "Who is in my life now that I am not fully appreciating?",
    "What part of today resisted being noticed, and what was it trying to show me?",
    "Did I eat, breathe, or move in a way that honored the body I have?",
    "What went right today that I failed to acknowledge?",
    "What small comfort do I enjoy that millions do not have?",
    "If I could relive one moment from today, which would I choose and why?",

    # Death & impermanence
    "Have I reconciled myself with the fact that I will die?",
    "What would I change tomorrow if I were told I had one month left?",
    "Am I living in a way I would not regret if it ended suddenly?",
    "What part of my life feels permanent that is actually temporary?",
    "If the people I love were taken tomorrow, did they know I loved them?",
    "Am I at peace with the person I am becoming?",
    "What am I still postponing that I should have done years ago?",
    "What is one thing I want to be said of me at the end of my life?",
    "Does the thought of death frighten me, and what does that fear reveal?",
    "What would die with me today that I have not yet shared or created?",
    "Am I more afraid of dying or of never having fully lived?",
    "What would those who knew me best say about how I lived?",
    "What would I want carved on my gravestone — and am I earning it?",
    "If I die having done exactly what I did today, was it enough?",
    "What is the thing I have been saying 'one day' to, and when is that day?",

    # Wisdom & learning
    "What did I learn today — not from a book, but from living?",
    "What was I wrong about recently, and what did I do with that realization?",
    "Am I learning from the wise, or only from the comfortable?",
    "What question am I not asking because I'm afraid of the answer?",
    "Who challenged my thinking today, and how did I respond?",
    "What belief do I hold that I have never seriously examined?",
    "What am I certain about that I should be more uncertain about?",
    "What does the wisest person I know do that I don't?",
    "Am I reading or thinking in a way that changes how I live?",
    "What pattern am I repeating that wisdom should have broken by now?",
    "What would I tell a younger version of myself about how to live?",
    "What advice am I giving others that I am not taking myself?",
    "What do I know I should do that I am still not doing?",
    "Am I growing, or am I simply accumulating experience without changing?",
    "What is the uncomfortable truth I am finally ready to face?",

    # Courage & action
    "What act of courage did I avoid today, and why?",
    "What am I waiting for permission to do that no one can grant but me?",
    "Did I speak when silence was cowardice?",
    "Did I stay silent when speaking was required?",
    "What would I attempt if I were not afraid of looking foolish?",
    "Where did I let fear make my decisions today?",
    "Am I going where the path leads, or where my heart calls?",
    "What is the bravest thing I could do this week?",
    "Did I stand up for something today, even at small cost?",
    "What would I do if I decided once and for all to stop waiting?",
    "What frontier of discomfort am I refusing to cross?",
    "Am I being bold enough in the only life I have?",
    "What would I try if failure carried no shame?",
    "Who needs me to be brave on their behalf, and am I?",
    "What have I been wanting to begin for years? What am I still waiting for?",

    # Self-knowledge
    "What emotion drove most of my behavior today — and was I aware of it at the time?",
    "What do I dislike in others that exists in me?",
    "What do I love in others that I have not developed in myself?",
    "What story am I telling about myself that may no longer be true?",
    "What do I pretend not to want that I secretly want very much?",
    "What am I afraid people would think if they could see inside my mind today?",
    "What would I discover about myself if I sat in silence for one hour?",
    "What am I avoiding knowing about myself?",
    "What does the way I spend my money reveal about my character?",
    "What does the way I treat strangers say about who I really am?",
    "If I had to describe my character honestly, what three words would I choose?",
    "What habit reveals a weakness I have not yet admitted?",
    "What do I want that I am ashamed to admit I want?",
    "Am I the same person in private as I am in public?",
    "What would I see if I watched myself live today from a distance?",

    # Discipline & daily practice
    "Did I do the one most important thing today before the urgent crowded it out?",
    "What did I practice today, intentionally?",
    "Where did distraction take time that discipline should have protected?",
    "Did I begin the day with intention, or with reaction?",
    "What is the single habit that would most change my life if I kept it?",
    "Am I consistent, or am I someone who is only good on good days?",
    "What would happen if I held myself to the same standards every single day?",
    "What did I let slide today that I have been pretending doesn't matter?",
    "How many hours of this day did I truly control?",
    "What does my morning routine say about what I value?",
    "What evening reflection am I skipping that I know I should keep?",
    "What would perfect daily discipline look like for me, and am I close to it?",
    "Where do I perform for others but not live up to it alone?",
    "What one action, repeated every day, would make me proud in a year?",
    "What is my biggest enemy to consistency, and what will I do about it?",

    # Community & duty
    "What did I contribute to my community today, not for praise but because it was right?",
    "Am I living only for myself, or in service of something larger?",
    "What burden is someone near me carrying that I could help lighten?",
    "Did I leave the people and places I touched today better than I found them?",
    "Am I fulfilling my responsibilities to those who depend on me?",
    "What sacrifice is required of me right now for the people I love?",
    "Who in my life needs a phone call, a visit, or a word of encouragement?",
    "What kind of neighbor, colleague, or citizen am I being?",
    "Where is my self-interest preventing me from doing what is right?",
    "What role do I play in the suffering of someone close to me?",
    "Who would suffer if I stopped showing up, and am I showing up fully?",
    "What would it mean to be truly useful today?",
    "Am I paying forward what others gave me when I needed it?",
    "What small act of kindness did I offer, unprompted, today?",
    "If everyone around me acted as I acted today, what kind of world would that be?",

    # Evening reflection
    "What went wrong today, and what is my role in it?",
    "What went right today, and to whom do I owe gratitude for it?",
    "What would I undo from today if I could?",
    "What will I do differently when tomorrow brings what today brought?",
    "Did today bring me closer to the person I want to become?",
    "What did I resist today that I should have embraced?",
    "What did I embrace today that I should have resisted?",
    "If I could send a message to myself at the start of today, what would I say?",
    "What did the discomfort of today prepare me for?",
    "What is the one lesson I must not forget from today?",
    "Am I ending this day with integrity — having given what I could?",
    "What is still unsettled in me, and what does that require of me?",
    "What will I carry into sleep that I should lay down before I sleep?",
    "What does the day I lived today say about the year I am building?",
    "If this were the last day of my life, was it a day worth living?",
]